// src/pages/Outputs.jsx
import React from 'react';
// Import the StatusPanel component for a richer output view
import StatusPanel from '../components/StatusPanel.jsx';

function Outputs() {
  // These URLs would dynamically change based on the simulation run selected
  const simulationStatus = 'Complete';
  const simulationMessage = 'Test: axi_read_write_test PASSED.';
  const waveformImageUrl = '/api/simulation/waveform_output.png';
  const vcdFileUrl = '/api/simulation/waveform_output.vcd';

  return (
    <div>
      <h1>📊 Simulation Outputs & Waveforms</h1>
      
      {/* 1. Status Panel (Enhanced) */}
      <StatusPanel 
        status={simulationStatus} 
        progress={100} // Assuming 100% since it's complete
        message={simulationMessage}
      />
      
      {/* 2. Waveform Image Display */}
      <section style={{ marginTop: '30px', padding: '20px', backgroundColor: '#2d2d30', borderRadius: '6px' }}>
        <h2>Waveform View (Static Snapshot)</h2>
        <p style={{ color: '#aaa', marginBottom: '15px' }}>
          **Static view** generated by the simulator backend for quick reference. For interactive analysis, download the raw VCD file.
        </p>
        
        {/* Displays the static image generated by the server */}
        <img 
          src={waveformImageUrl} 
          alt="Simulated Waveforms" 
          style={{ width: '100%', border: '1px solid #3f3f46' }}
        />
        
        {/* Action Button */}
        <div style={{ marginTop: '20px', textAlign: 'right' }}>
          <a href={vcdFileUrl} download style={{ textDecoration: 'none' }}>
            <button>
              ⬇️ Download Raw VCD File
            </button>
          </a>
        </div>
      </section>
      
      {/* 3. Placeholder for Log/Report Viewer (CodeViewer component would go here) */}
      {/* <CodeViewer title="Simulation Log" code={logContent} /> */}

    </div>
  );
}

export default Outputs;